### ISSUE TITLE
话说 我们几个人的客户端要不要合并下

### ISSUE THREAD

**Issue by jim-kirisame** [jiangming1399/GdutCom#1]
@lindexi

@chenhaowen01

**Comment by xnhw01** [comment]
可以啊，我建议使用gdut-drcom作为GdutCOM的命令行后端

**Comment by lindexi** [comment]
如果大神希望的话，我没意见

**Comment by lindexi** [comment]
可以让我参加？

**Comment by lindexi** [comment]
@lyhyl 大神，你也来不？

**Comment by jim-kirisame** [comment]
我创建一个团队邀请你们吧

**Comment by jim-kirisame** [comment]
现在是怎么弄呢？以哪个版本作为基版本开发比较好呢？

**Comment by lyhyl** [comment]
我觉得分离PPPoE跟心跳就好了，PPPoE用C#写好了，现在心跳包我都是用可用的py，然后用py2exe包装一下就好了（不介意性能的话）

**Comment by jim-kirisame** [comment]
我觉得py2exe的依赖比较难解决，还是用楼上的gdut-drcom项目比较稳妥一点

**Comment by lyhyl** [comment]
py2exe没有太大依赖啊……，不需要py环境的

**Comment by jim-kirisame** [comment]
之前试过直接用py2exe打包，拷贝到其他同学的电脑上就没法运行了

**Comment by jim-kirisame** [comment]
（咱们有更方便的讨论方式吗）

**Comment by lyhyl** [comment]
也是好事，重要的是是要合并一下了。

**Comment by xnhw01** [comment]
gdut-drcom只依赖c库

**Comment by xnhw01** [comment]
静态编译也可以

**Comment by xnhw01** [comment]
而且py的项目错误处理并不好

**Comment by lyhyl** [comment]
c吧，选好了，还有，我看到 @lindexi 用的是MVVM模型？好像不错。

**Comment by jim-kirisame** [comment]
我已经邀请你们了
https://github.com/GDUT-Drcom

**Comment by lindexi** [comment]
我的也是python转换心跳包，我是渣渣没有自己写心跳
